model:
  type: monai
  _target_: monai.networks.nets.SegResNetDS
  spatial_dims: 3
  init_filters: 32
  in_channels: 1
  out_channels: ${num_classes}
  blocks_down: [1, 2, 2, 2, 2, 4]
  norm: INSTANCE_NVFUSER
  dsdepth: 4

loss:
  type: monai
  _target_: monai.losses.DeepSupervisionLoss
  loss: ${loss_function}

post_transforms:
  train:
    _target_: ignition.data.monai.DSGetFirstd
    keys: ['pred', 'label']