# evaluate means we include the original labels and save them along with the predictions, potentially mapped

debug: false
seed: 777 # random seed
output_dir: ./results

mode: eval
task: segmentation # task type, only supports segmentation for now
model_type: ignition # model type. If `ignition`, trained through this library. If 
model_dir: logs/${name}
backend: nccl
engine_type: monai  # monai

inferer:  # set to null to disable sliding window inference
  _target_: monai.inferers.SlidingWindowInferer
  roi_size: ${roi_size} # roi size for inference
  sw_batch_size: ${eval_batch_size} # sliding window batch size
  overlap: 0.25
  mode: 'constant' # blending mode, can be 'constant' or 'gaussian'
  sigma_scale: 0.125 # scale for gaussian blending, only used if mode is 'gaussian'
  progress: true # show progress bar during inference


default_post_transforms: # TODO: Check if model already does a softmax? may need to add activation here
  
default_metrics:
  list:
  - _target_: monai.handlers.MeanDice
    _key_: mean_dice
    include_background: true
    reduction: mean_batch
    return_with_label: true
    output_transform: 
      _target_: monai.handlers.from_engine
      keys: ['pred', 'label']  # keys to extract from the output
  - _target_: monai.handlers.MeanDice
    _key_: mean_dice_fg
    include_background: false
    output_transform: 
      _target_: monai.handlers.from_engine
      keys: ['pred', 'label']  # keys to extract from the output
  - _target_: monai.handlers.MeanIoUHandler
    _key_: mean_iou
    include_background: true
    output_transform: 
      _target_: monai.handlers.from_engine
      keys: ['pred', 'label']  # keys to extract from the output
  - _target_: monai.handlers.ConfusionMatrix
    _key_: conf_matrix  # TODO: Implement conf matrix with all metrics
    metric_name: "f1 score"
    include_background: true
    output_transform:
      _target_: monai.handlers.from_engine
      keys: ['pred', 'label']  # keys to extract from the output
  key_metric_name: ${metrics.list[0]._key_} # name of the key metric for validation, used for early stopping and checkpointing

default_engine_handlers:
  - _target_: monai.handlers.MetricsSaver
    save_dir: ${output_dir}