seed: 777 # random seed
data_path: /Users/daniel/data/ # input data path
batch_size: 48 # train batch size
eval_batch_size: 32 # evaluation batch size
num_workers: 10 # number of subprocesses to use for data loading
max_epochs: 100 # number of maximum epochs
use_amp: false # use AMP (Automatic Mixed Precision)
debug: false
train_epoch_length: null
eval_epoch_length: null
filename_prefix: training
n_saved: 2
save_every_iters: 1000
patience: 5
output_dir: ./logs
log_every_iters: 10
lr: 0.02 # learning rate
accumulation_steps: 1 # parameter for gradient accumulation
eval_every_epochs: 10 # evaluate every n epochs
num_classes: 21 # number of classes for segmentation
data_subset_size: 0.1 # subset size for data, 0.1 means 10% of the data. If set to null, the full dataset is used
backend: gloo
model:
  type: torchvision # model type
  name: deeplabv3_mobilenet_v3_large # model name
  pretrained: true # use pretrained weights