#@package _global_
mode: train
debug: false
seed: 777 # random seed
output_dir: ./logs
output_prefix: ${name}
wandb_logging: true
engine_type: monai
backend: nccl
task: segmentation # task type, only supports segmentation for now
inferer:  # set to null to disable sliding window inference

metrics:
  val:  # by default, the first metric is used as the 'key' metric
    - _target_: monai.handlers.MeanDice
      _key_: mean_dice_fg
      include_background: false
      output_transform: 
        _target_: monai.handlers.from_engine
        keys: ['pred', 'label']  # keys to extract from the output
    - _target_: monai.handlers.MeanDice
      _key_: mean_dice
      include_background: true
      output_transform: 
        _target_: monai.handlers.from_engine
        keys: ['pred', 'label']  # keys to extract from the output
    - _target_: monai.handlers.MeanIoUHandler
      _key_: mean_iou
      include_background: true
      output_transform: 
        _target_: monai.handlers.from_engine
        keys: ['pred', 'label']  # keys to extract from the output
    - _target_: monai.handlers.ConfusionMatrix
      _key_: conf_matrix  # TODO: Implement conf matrix with all metrics
      metric_name: "f1 score"
      include_background: true
      output_transform:
        _target_: monai.handlers.from_engine
        keys: ['pred', 'label']  # keys to extract from the output
  train:
    - _target_: monai.handlers.IgniteMetricHandler
      _key_: train_loss
      _requires_: loss_fn
      output_transform:
        _target_: monai.handlers.from_engine
        keys: ['pred', 'label']
  val_key_metric_name: ${metrics.val[0]._key_} # name of the key metric for validation, used for early stopping and checkpointing
  train_key_metric_name: ${metrics.train[0]._key_} # name of the key metric for training, used for logging