train: null  # could perhaps do the keeplargestconnectedcomponent
val:  # TODO: Check if model already does a softmax? may need to add activation here
  _target_: monai.transforms.Compose
  transforms:
    - _target_: monai.transforms.Activationsd
      keys: ['pred']  # keys to apply the activation to
      softmax: true
    - _target_: monai.transforms.AsDiscreted
      keys: ['pred']  # keys to apply the discretization to
      argmax: true  # apply argmax to the predictions
      to_onehot: ${num_classes}  # convert to one-hot encoding  -- already one-hot from output
      include_background: true  # include background class in the discretization
      # keepdims: true
      # maybe we need a threshold here? or still argmax?
    # - _target_: ignition.transforms.Debugd
    #   keys: ['pred']
    - _target_: monai.transforms.AsDiscreted
      keys: ['label']  # keys to apply the discretization to
      argmax: false  # apply argmax to the predictions
      to_onehot: ${num_classes}  # convert to one-hot encoding
      include_background: true  # include background class in the discretization